/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace AgentRegistry {
      
    export type AgentStruct = {wallet: AddressLike, agentType: BigNumberish, name: string, description: string, capabilitiesURI: string, registeredAt: BigNumberish, active: boolean}

    export type AgentStructOutput = [wallet: string, agentType: bigint, name: string, description: string, capabilitiesURI: string, registeredAt: bigint, active: boolean] & {wallet: string, agentType: bigint, name: string, description: string, capabilitiesURI: string, registeredAt: bigint, active: boolean }
  

    export type FeedbackStruct = {submitter: AddressLike, agentId: BigNumberish, score: BigNumberish, tag: string, uri: string, timestamp: BigNumberish}

    export type FeedbackStructOutput = [submitter: string, agentId: bigint, score: bigint, tag: string, uri: string, timestamp: bigint] & {submitter: string, agentId: bigint, score: bigint, tag: string, uri: string, timestamp: bigint }
  
    }

  export interface AgentRegistryInterface extends Interface {
    getFunction(nameOrSignature: "agentFeedbackCount" | "agentFeedbacks" | "agentReputationSum" | "agentValidations" | "agents" | "approve" | "balanceOf" | "deactivateAgent" | "fulfillValidation" | "getAgent" | "getAgentByWallet" | "getAgentFeedbacks" | "getApproved" | "getReputationScore" | "isApprovedForAll" | "isRegisteredAgent" | "name" | "owner" | "ownerOf" | "registerAgent" | "renounceOwnership" | "requestValidation" | "safeTransferFrom(address,address,uint256)" | "safeTransferFrom(address,address,uint256,bytes)" | "setApprovalForAll" | "submitFeedback" | "supportsInterface" | "symbol" | "tokenURI" | "totalAgents" | "transferFrom" | "transferOwnership" | "walletToAgentId"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "AgentDeactivated" | "AgentRegistered" | "Approval" | "ApprovalForAll" | "BatchMetadataUpdate" | "FeedbackSubmitted" | "MetadataUpdate" | "OwnershipTransferred" | "Transfer" | "ValidationFulfilled" | "ValidationRequested"): EventFragment;

    encodeFunctionData(functionFragment: 'agentFeedbackCount', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'agentFeedbacks', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'agentReputationSum', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'agentValidations', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'agents', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'approve', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'balanceOf', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'deactivateAgent', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'fulfillValidation', values: [BigNumberish, BigNumberish, string, BigNumberish]): string;
encodeFunctionData(functionFragment: 'getAgent', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getAgentByWallet', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getAgentFeedbacks', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getApproved', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getReputationScore', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'isApprovedForAll', values: [AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'isRegisteredAgent', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'name', values?: undefined): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'ownerOf', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'registerAgent', values: [BigNumberish, string, string, string, string]): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'requestValidation', values: [BigNumberish, string]): string;
encodeFunctionData(functionFragment: 'safeTransferFrom(address,address,uint256)', values: [AddressLike, AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'safeTransferFrom(address,address,uint256,bytes)', values: [AddressLike, AddressLike, BigNumberish, BytesLike]): string;
encodeFunctionData(functionFragment: 'setApprovalForAll', values: [AddressLike, boolean]): string;
encodeFunctionData(functionFragment: 'submitFeedback', values: [BigNumberish, BigNumberish, string, string]): string;
encodeFunctionData(functionFragment: 'supportsInterface', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'symbol', values?: undefined): string;
encodeFunctionData(functionFragment: 'tokenURI', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'totalAgents', values?: undefined): string;
encodeFunctionData(functionFragment: 'transferFrom', values: [AddressLike, AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'walletToAgentId', values: [AddressLike]): string;

    decodeFunctionResult(functionFragment: 'agentFeedbackCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'agentFeedbacks', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'agentReputationSum', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'agentValidations', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'agents', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'approve', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'balanceOf', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'deactivateAgent', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'fulfillValidation', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getAgent', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getAgentByWallet', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getAgentFeedbacks', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getApproved', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getReputationScore', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isApprovedForAll', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isRegisteredAgent', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'name', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'ownerOf', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'registerAgent', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'requestValidation', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'safeTransferFrom(address,address,uint256)', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'safeTransferFrom(address,address,uint256,bytes)', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setApprovalForAll', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'submitFeedback', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'supportsInterface', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'symbol', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'tokenURI', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalAgents', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferFrom', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'walletToAgentId', data: BytesLike): Result;
  }

  
    export namespace AgentDeactivatedEvent {
      export type InputTuple = [agentId: BigNumberish, timestamp: BigNumberish];
      export type OutputTuple = [agentId: bigint, timestamp: bigint];
      export interface OutputObject {agentId: bigint, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace AgentRegisteredEvent {
      export type InputTuple = [agentId: BigNumberish, wallet: AddressLike, agentType: BigNumberish, name: string, timestamp: BigNumberish];
      export type OutputTuple = [agentId: bigint, wallet: string, agentType: bigint, name: string, timestamp: bigint];
      export interface OutputObject {agentId: bigint, wallet: string, agentType: bigint, name: string, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ApprovalEvent {
      export type InputTuple = [owner: AddressLike, approved: AddressLike, tokenId: BigNumberish];
      export type OutputTuple = [owner: string, approved: string, tokenId: bigint];
      export interface OutputObject {owner: string, approved: string, tokenId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ApprovalForAllEvent {
      export type InputTuple = [owner: AddressLike, operator: AddressLike, approved: boolean];
      export type OutputTuple = [owner: string, operator: string, approved: boolean];
      export interface OutputObject {owner: string, operator: string, approved: boolean };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace BatchMetadataUpdateEvent {
      export type InputTuple = [_fromTokenId: BigNumberish, _toTokenId: BigNumberish];
      export type OutputTuple = [_fromTokenId: bigint, _toTokenId: bigint];
      export interface OutputObject {_fromTokenId: bigint, _toTokenId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace FeedbackSubmittedEvent {
      export type InputTuple = [agentId: BigNumberish, submitter: AddressLike, score: BigNumberish, tag: string, timestamp: BigNumberish];
      export type OutputTuple = [agentId: bigint, submitter: string, score: bigint, tag: string, timestamp: bigint];
      export interface OutputObject {agentId: bigint, submitter: string, score: bigint, tag: string, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace MetadataUpdateEvent {
      export type InputTuple = [_tokenId: BigNumberish];
      export type OutputTuple = [_tokenId: bigint];
      export interface OutputObject {_tokenId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TransferEvent {
      export type InputTuple = [from: AddressLike, to: AddressLike, tokenId: BigNumberish];
      export type OutputTuple = [from: string, to: string, tokenId: bigint];
      export interface OutputObject {from: string, to: string, tokenId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ValidationFulfilledEvent {
      export type InputTuple = [agentId: BigNumberish, validationIndex: BigNumberish, result: BigNumberish, timestamp: BigNumberish];
      export type OutputTuple = [agentId: bigint, validationIndex: bigint, result: bigint, timestamp: bigint];
      export interface OutputObject {agentId: bigint, validationIndex: bigint, result: bigint, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ValidationRequestedEvent {
      export type InputTuple = [agentId: BigNumberish, requester: AddressLike, validationIndex: BigNumberish, timestamp: BigNumberish];
      export type OutputTuple = [agentId: bigint, requester: string, validationIndex: bigint, timestamp: bigint];
      export interface OutputObject {agentId: bigint, requester: string, validationIndex: bigint, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface AgentRegistry extends BaseContract {
    
    connect(runner?: ContractRunner | null): AgentRegistry;
    waitForDeployment(): Promise<this>;

    interface: AgentRegistryInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    agentFeedbackCount: TypedContractMethod<
      [arg0: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    agentFeedbacks: TypedContractMethod<
      [arg0: BigNumberish, arg1: BigNumberish, ],
      [[string, bigint, bigint, string, string, bigint] & {submitter: string, agentId: bigint, score: bigint, tag: string, uri: string, timestamp: bigint }],
      'view'
    >
    

    
    agentReputationSum: TypedContractMethod<
      [arg0: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    agentValidations: TypedContractMethod<
      [arg0: BigNumberish, arg1: BigNumberish, ],
      [[bigint, string, string, boolean, string, bigint, bigint] & {agentId: bigint, requester: string, requestURI: string, fulfilled: boolean, responseURI: string, result: bigint, timestamp: bigint }],
      'view'
    >
    

    
    agents: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, bigint, string, string, string, bigint, boolean] & {wallet: string, agentType: bigint, name: string, description: string, capabilitiesURI: string, registeredAt: bigint, active: boolean }],
      'view'
    >
    

    
    approve: TypedContractMethod<
      [to: AddressLike, tokenId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    balanceOf: TypedContractMethod<
      [owner: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    deactivateAgent: TypedContractMethod<
      [_agentId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    fulfillValidation: TypedContractMethod<
      [_agentId: BigNumberish, _validationIndex: BigNumberish, _responseURI: string, _result: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    getAgent: TypedContractMethod<
      [_agentId: BigNumberish, ],
      [AgentRegistry.AgentStructOutput],
      'view'
    >
    

    
    getAgentByWallet: TypedContractMethod<
      [_wallet: AddressLike, ],
      [AgentRegistry.AgentStructOutput],
      'view'
    >
    

    
    getAgentFeedbacks: TypedContractMethod<
      [_agentId: BigNumberish, ],
      [AgentRegistry.FeedbackStructOutput[]],
      'view'
    >
    

    
    getApproved: TypedContractMethod<
      [tokenId: BigNumberish, ],
      [string],
      'view'
    >
    

    
    getReputationScore: TypedContractMethod<
      [_agentId: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    isApprovedForAll: TypedContractMethod<
      [owner: AddressLike, operator: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    isRegisteredAgent: TypedContractMethod<
      [_wallet: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    name: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    ownerOf: TypedContractMethod<
      [tokenId: BigNumberish, ],
      [string],
      'view'
    >
    

    
    registerAgent: TypedContractMethod<
      [_agentType: BigNumberish, _name: string, _description: string, _capabilitiesURI: string, _tokenURI: string, ],
      [bigint],
      'nonpayable'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    requestValidation: TypedContractMethod<
      [_agentId: BigNumberish, _requestURI: string, ],
      [bigint],
      'nonpayable'
    >
    

    
    "safeTransferFrom(address,address,uint256)": TypedContractMethod<
      [from: AddressLike, to: AddressLike, tokenId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    "safeTransferFrom(address,address,uint256,bytes)": TypedContractMethod<
      [from: AddressLike, to: AddressLike, tokenId: BigNumberish, data: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    setApprovalForAll: TypedContractMethod<
      [operator: AddressLike, approved: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    submitFeedback: TypedContractMethod<
      [_agentId: BigNumberish, _score: BigNumberish, _tag: string, _uri: string, ],
      [void],
      'nonpayable'
    >
    

    
    supportsInterface: TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >
    

    
    symbol: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    tokenURI: TypedContractMethod<
      [tokenId: BigNumberish, ],
      [string],
      'view'
    >
    

    
    totalAgents: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    transferFrom: TypedContractMethod<
      [from: AddressLike, to: AddressLike, tokenId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    walletToAgentId: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'agentFeedbackCount'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'agentFeedbacks'): TypedContractMethod<
      [arg0: BigNumberish, arg1: BigNumberish, ],
      [[string, bigint, bigint, string, string, bigint] & {submitter: string, agentId: bigint, score: bigint, tag: string, uri: string, timestamp: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'agentReputationSum'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'agentValidations'): TypedContractMethod<
      [arg0: BigNumberish, arg1: BigNumberish, ],
      [[bigint, string, string, boolean, string, bigint, bigint] & {agentId: bigint, requester: string, requestURI: string, fulfilled: boolean, responseURI: string, result: bigint, timestamp: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'agents'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, bigint, string, string, string, bigint, boolean] & {wallet: string, agentType: bigint, name: string, description: string, capabilitiesURI: string, registeredAt: bigint, active: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'approve'): TypedContractMethod<
      [to: AddressLike, tokenId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'balanceOf'): TypedContractMethod<
      [owner: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'deactivateAgent'): TypedContractMethod<
      [_agentId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'fulfillValidation'): TypedContractMethod<
      [_agentId: BigNumberish, _validationIndex: BigNumberish, _responseURI: string, _result: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getAgent'): TypedContractMethod<
      [_agentId: BigNumberish, ],
      [AgentRegistry.AgentStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getAgentByWallet'): TypedContractMethod<
      [_wallet: AddressLike, ],
      [AgentRegistry.AgentStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getAgentFeedbacks'): TypedContractMethod<
      [_agentId: BigNumberish, ],
      [AgentRegistry.FeedbackStructOutput[]],
      'view'
    >;
getFunction(nameOrSignature: 'getApproved'): TypedContractMethod<
      [tokenId: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getReputationScore'): TypedContractMethod<
      [_agentId: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'isApprovedForAll'): TypedContractMethod<
      [owner: AddressLike, operator: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'isRegisteredAgent'): TypedContractMethod<
      [_wallet: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'name'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'ownerOf'): TypedContractMethod<
      [tokenId: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'registerAgent'): TypedContractMethod<
      [_agentType: BigNumberish, _name: string, _description: string, _capabilitiesURI: string, _tokenURI: string, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'requestValidation'): TypedContractMethod<
      [_agentId: BigNumberish, _requestURI: string, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'safeTransferFrom(address,address,uint256)'): TypedContractMethod<
      [from: AddressLike, to: AddressLike, tokenId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'safeTransferFrom(address,address,uint256,bytes)'): TypedContractMethod<
      [from: AddressLike, to: AddressLike, tokenId: BigNumberish, data: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setApprovalForAll'): TypedContractMethod<
      [operator: AddressLike, approved: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'submitFeedback'): TypedContractMethod<
      [_agentId: BigNumberish, _score: BigNumberish, _tag: string, _uri: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'supportsInterface'): TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'symbol'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'tokenURI'): TypedContractMethod<
      [tokenId: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'totalAgents'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'transferFrom'): TypedContractMethod<
      [from: AddressLike, to: AddressLike, tokenId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'walletToAgentId'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;

    getEvent(key: 'AgentDeactivated'): TypedContractEvent<AgentDeactivatedEvent.InputTuple, AgentDeactivatedEvent.OutputTuple, AgentDeactivatedEvent.OutputObject>;
getEvent(key: 'AgentRegistered'): TypedContractEvent<AgentRegisteredEvent.InputTuple, AgentRegisteredEvent.OutputTuple, AgentRegisteredEvent.OutputObject>;
getEvent(key: 'Approval'): TypedContractEvent<ApprovalEvent.InputTuple, ApprovalEvent.OutputTuple, ApprovalEvent.OutputObject>;
getEvent(key: 'ApprovalForAll'): TypedContractEvent<ApprovalForAllEvent.InputTuple, ApprovalForAllEvent.OutputTuple, ApprovalForAllEvent.OutputObject>;
getEvent(key: 'BatchMetadataUpdate'): TypedContractEvent<BatchMetadataUpdateEvent.InputTuple, BatchMetadataUpdateEvent.OutputTuple, BatchMetadataUpdateEvent.OutputObject>;
getEvent(key: 'FeedbackSubmitted'): TypedContractEvent<FeedbackSubmittedEvent.InputTuple, FeedbackSubmittedEvent.OutputTuple, FeedbackSubmittedEvent.OutputObject>;
getEvent(key: 'MetadataUpdate'): TypedContractEvent<MetadataUpdateEvent.InputTuple, MetadataUpdateEvent.OutputTuple, MetadataUpdateEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
getEvent(key: 'Transfer'): TypedContractEvent<TransferEvent.InputTuple, TransferEvent.OutputTuple, TransferEvent.OutputObject>;
getEvent(key: 'ValidationFulfilled'): TypedContractEvent<ValidationFulfilledEvent.InputTuple, ValidationFulfilledEvent.OutputTuple, ValidationFulfilledEvent.OutputObject>;
getEvent(key: 'ValidationRequested'): TypedContractEvent<ValidationRequestedEvent.InputTuple, ValidationRequestedEvent.OutputTuple, ValidationRequestedEvent.OutputObject>;

    filters: {
      
      'AgentDeactivated(uint256,uint256)': TypedContractEvent<AgentDeactivatedEvent.InputTuple, AgentDeactivatedEvent.OutputTuple, AgentDeactivatedEvent.OutputObject>;
      AgentDeactivated: TypedContractEvent<AgentDeactivatedEvent.InputTuple, AgentDeactivatedEvent.OutputTuple, AgentDeactivatedEvent.OutputObject>;
    

      'AgentRegistered(uint256,address,uint8,string,uint256)': TypedContractEvent<AgentRegisteredEvent.InputTuple, AgentRegisteredEvent.OutputTuple, AgentRegisteredEvent.OutputObject>;
      AgentRegistered: TypedContractEvent<AgentRegisteredEvent.InputTuple, AgentRegisteredEvent.OutputTuple, AgentRegisteredEvent.OutputObject>;
    

      'Approval(address,address,uint256)': TypedContractEvent<ApprovalEvent.InputTuple, ApprovalEvent.OutputTuple, ApprovalEvent.OutputObject>;
      Approval: TypedContractEvent<ApprovalEvent.InputTuple, ApprovalEvent.OutputTuple, ApprovalEvent.OutputObject>;
    

      'ApprovalForAll(address,address,bool)': TypedContractEvent<ApprovalForAllEvent.InputTuple, ApprovalForAllEvent.OutputTuple, ApprovalForAllEvent.OutputObject>;
      ApprovalForAll: TypedContractEvent<ApprovalForAllEvent.InputTuple, ApprovalForAllEvent.OutputTuple, ApprovalForAllEvent.OutputObject>;
    

      'BatchMetadataUpdate(uint256,uint256)': TypedContractEvent<BatchMetadataUpdateEvent.InputTuple, BatchMetadataUpdateEvent.OutputTuple, BatchMetadataUpdateEvent.OutputObject>;
      BatchMetadataUpdate: TypedContractEvent<BatchMetadataUpdateEvent.InputTuple, BatchMetadataUpdateEvent.OutputTuple, BatchMetadataUpdateEvent.OutputObject>;
    

      'FeedbackSubmitted(uint256,address,uint8,string,uint256)': TypedContractEvent<FeedbackSubmittedEvent.InputTuple, FeedbackSubmittedEvent.OutputTuple, FeedbackSubmittedEvent.OutputObject>;
      FeedbackSubmitted: TypedContractEvent<FeedbackSubmittedEvent.InputTuple, FeedbackSubmittedEvent.OutputTuple, FeedbackSubmittedEvent.OutputObject>;
    

      'MetadataUpdate(uint256)': TypedContractEvent<MetadataUpdateEvent.InputTuple, MetadataUpdateEvent.OutputTuple, MetadataUpdateEvent.OutputObject>;
      MetadataUpdate: TypedContractEvent<MetadataUpdateEvent.InputTuple, MetadataUpdateEvent.OutputTuple, MetadataUpdateEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    

      'Transfer(address,address,uint256)': TypedContractEvent<TransferEvent.InputTuple, TransferEvent.OutputTuple, TransferEvent.OutputObject>;
      Transfer: TypedContractEvent<TransferEvent.InputTuple, TransferEvent.OutputTuple, TransferEvent.OutputObject>;
    

      'ValidationFulfilled(uint256,uint256,uint8,uint256)': TypedContractEvent<ValidationFulfilledEvent.InputTuple, ValidationFulfilledEvent.OutputTuple, ValidationFulfilledEvent.OutputObject>;
      ValidationFulfilled: TypedContractEvent<ValidationFulfilledEvent.InputTuple, ValidationFulfilledEvent.OutputTuple, ValidationFulfilledEvent.OutputObject>;
    

      'ValidationRequested(uint256,address,uint256,uint256)': TypedContractEvent<ValidationRequestedEvent.InputTuple, ValidationRequestedEvent.OutputTuple, ValidationRequestedEvent.OutputObject>;
      ValidationRequested: TypedContractEvent<ValidationRequestedEvent.InputTuple, ValidationRequestedEvent.OutputTuple, ValidationRequestedEvent.OutputObject>;
    
    };
  }