/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace DesignRegistry {
      
    export type DesignStruct = {artist: AddressLike, title: string, description: string, category: string, ipfsCid: string, tags: string[], thresholdPrice: BigNumberish, createdAt: BigNumberish, isPublic: boolean}

    export type DesignStructOutput = [artist: string, title: string, description: string, category: string, ipfsCid: string, tags: string[], thresholdPrice: bigint, createdAt: bigint, isPublic: boolean] & {artist: string, title: string, description: string, category: string, ipfsCid: string, tags: string[], thresholdPrice: bigint, createdAt: bigint, isPublic: boolean }
  

    export type ArtifactStruct = {name: string, description: string, priceInWei: BigNumberish, active: boolean}

    export type ArtifactStructOutput = [name: string, description: string, priceInWei: bigint, active: boolean] & {name: string, description: string, priceInWei: bigint, active: boolean }
  
    }

  export interface DesignRegistryInterface extends Interface {
    getFunction(nameOrSignature: "addArtifact" | "approve" | "artistDesigns" | "balanceOf" | "calculateArtifactsCost" | "designArtifacts" | "designs" | "getApproved" | "getArtifactCount" | "getArtistDesigns" | "getDesign" | "getDesignArtifacts" | "isApprovedForAll" | "mintDesign" | "name" | "owner" | "ownerOf" | "renounceOwnership" | "safeTransferFrom(address,address,uint256)" | "safeTransferFrom(address,address,uint256,bytes)" | "setApprovalForAll" | "supportsInterface" | "symbol" | "toggleArtifact" | "tokenURI" | "totalDesigns" | "transferFrom" | "transferOwnership" | "updateArtifactPrice"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "Approval" | "ApprovalForAll" | "ArtifactAdded" | "ArtifactUpdated" | "BatchMetadataUpdate" | "DesignMinted" | "MetadataUpdate" | "OwnershipTransferred" | "ThresholdPriceUpdated" | "Transfer"): EventFragment;

    encodeFunctionData(functionFragment: 'addArtifact', values: [BigNumberish, string, string, BigNumberish]): string;
encodeFunctionData(functionFragment: 'approve', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'artistDesigns', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'balanceOf', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'calculateArtifactsCost', values: [BigNumberish, BigNumberish[]]): string;
encodeFunctionData(functionFragment: 'designArtifacts', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'designs', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getApproved', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getArtifactCount', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getArtistDesigns', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getDesign', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getDesignArtifacts', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'isApprovedForAll', values: [AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'mintDesign', values: [string, string, string, string, string[], string]): string;
encodeFunctionData(functionFragment: 'name', values?: undefined): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'ownerOf', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'safeTransferFrom(address,address,uint256)', values: [AddressLike, AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'safeTransferFrom(address,address,uint256,bytes)', values: [AddressLike, AddressLike, BigNumberish, BytesLike]): string;
encodeFunctionData(functionFragment: 'setApprovalForAll', values: [AddressLike, boolean]): string;
encodeFunctionData(functionFragment: 'supportsInterface', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'symbol', values?: undefined): string;
encodeFunctionData(functionFragment: 'toggleArtifact', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'tokenURI', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'totalDesigns', values?: undefined): string;
encodeFunctionData(functionFragment: 'transferFrom', values: [AddressLike, AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'updateArtifactPrice', values: [BigNumberish, BigNumberish, BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'addArtifact', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'approve', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'artistDesigns', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'balanceOf', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'calculateArtifactsCost', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'designArtifacts', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'designs', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getApproved', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getArtifactCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getArtistDesigns', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getDesign', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getDesignArtifacts', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isApprovedForAll', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'mintDesign', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'name', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'ownerOf', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'safeTransferFrom(address,address,uint256)', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'safeTransferFrom(address,address,uint256,bytes)', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setApprovalForAll', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'supportsInterface', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'symbol', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'toggleArtifact', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'tokenURI', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalDesigns', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferFrom', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updateArtifactPrice', data: BytesLike): Result;
  }

  
    export namespace ApprovalEvent {
      export type InputTuple = [owner: AddressLike, approved: AddressLike, tokenId: BigNumberish];
      export type OutputTuple = [owner: string, approved: string, tokenId: bigint];
      export interface OutputObject {owner: string, approved: string, tokenId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ApprovalForAllEvent {
      export type InputTuple = [owner: AddressLike, operator: AddressLike, approved: boolean];
      export type OutputTuple = [owner: string, operator: string, approved: boolean];
      export interface OutputObject {owner: string, operator: string, approved: boolean };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ArtifactAddedEvent {
      export type InputTuple = [designId: BigNumberish, artifactIndex: BigNumberish, name: string, priceInWei: BigNumberish];
      export type OutputTuple = [designId: bigint, artifactIndex: bigint, name: string, priceInWei: bigint];
      export interface OutputObject {designId: bigint, artifactIndex: bigint, name: string, priceInWei: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ArtifactUpdatedEvent {
      export type InputTuple = [designId: BigNumberish, artifactIndex: BigNumberish, newPrice: BigNumberish];
      export type OutputTuple = [designId: bigint, artifactIndex: bigint, newPrice: bigint];
      export interface OutputObject {designId: bigint, artifactIndex: bigint, newPrice: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace BatchMetadataUpdateEvent {
      export type InputTuple = [_fromTokenId: BigNumberish, _toTokenId: BigNumberish];
      export type OutputTuple = [_fromTokenId: bigint, _toTokenId: bigint];
      export interface OutputObject {_fromTokenId: bigint, _toTokenId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace DesignMintedEvent {
      export type InputTuple = [tokenId: BigNumberish, artist: AddressLike, title: string, ipfsCid: string, timestamp: BigNumberish];
      export type OutputTuple = [tokenId: bigint, artist: string, title: string, ipfsCid: string, timestamp: bigint];
      export interface OutputObject {tokenId: bigint, artist: string, title: string, ipfsCid: string, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace MetadataUpdateEvent {
      export type InputTuple = [_tokenId: BigNumberish];
      export type OutputTuple = [_tokenId: bigint];
      export interface OutputObject {_tokenId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ThresholdPriceUpdatedEvent {
      export type InputTuple = [designId: BigNumberish, newThreshold: BigNumberish];
      export type OutputTuple = [designId: bigint, newThreshold: bigint];
      export interface OutputObject {designId: bigint, newThreshold: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TransferEvent {
      export type InputTuple = [from: AddressLike, to: AddressLike, tokenId: BigNumberish];
      export type OutputTuple = [from: string, to: string, tokenId: bigint];
      export interface OutputObject {from: string, to: string, tokenId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface DesignRegistry extends BaseContract {
    
    connect(runner?: ContractRunner | null): DesignRegistry;
    waitForDeployment(): Promise<this>;

    interface: DesignRegistryInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    addArtifact: TypedContractMethod<
      [_designId: BigNumberish, _name: string, _description: string, _priceInWei: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    approve: TypedContractMethod<
      [to: AddressLike, tokenId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    artistDesigns: TypedContractMethod<
      [arg0: AddressLike, arg1: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    balanceOf: TypedContractMethod<
      [owner: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    calculateArtifactsCost: TypedContractMethod<
      [_designId: BigNumberish, _artifactIds: BigNumberish[], ],
      [bigint],
      'view'
    >
    

    
    designArtifacts: TypedContractMethod<
      [arg0: BigNumberish, arg1: BigNumberish, ],
      [[string, string, bigint, boolean] & {name: string, description: string, priceInWei: bigint, active: boolean }],
      'view'
    >
    

    
    designs: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, string, string, string, string, bigint, bigint, boolean] & {artist: string, title: string, description: string, category: string, ipfsCid: string, thresholdPrice: bigint, createdAt: bigint, isPublic: boolean }],
      'view'
    >
    

    
    getApproved: TypedContractMethod<
      [tokenId: BigNumberish, ],
      [string],
      'view'
    >
    

    
    getArtifactCount: TypedContractMethod<
      [_designId: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    getArtistDesigns: TypedContractMethod<
      [_artist: AddressLike, ],
      [bigint[]],
      'view'
    >
    

    
    getDesign: TypedContractMethod<
      [_designId: BigNumberish, ],
      [DesignRegistry.DesignStructOutput],
      'view'
    >
    

    
    getDesignArtifacts: TypedContractMethod<
      [_designId: BigNumberish, ],
      [DesignRegistry.ArtifactStructOutput[]],
      'view'
    >
    

    
    isApprovedForAll: TypedContractMethod<
      [owner: AddressLike, operator: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    mintDesign: TypedContractMethod<
      [_title: string, _description: string, _category: string, _ipfsCid: string, _tags: string[], _tokenURI: string, ],
      [bigint],
      'nonpayable'
    >
    

    
    name: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    ownerOf: TypedContractMethod<
      [tokenId: BigNumberish, ],
      [string],
      'view'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    "safeTransferFrom(address,address,uint256)": TypedContractMethod<
      [from: AddressLike, to: AddressLike, tokenId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    "safeTransferFrom(address,address,uint256,bytes)": TypedContractMethod<
      [from: AddressLike, to: AddressLike, tokenId: BigNumberish, data: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    setApprovalForAll: TypedContractMethod<
      [operator: AddressLike, approved: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    supportsInterface: TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >
    

    
    symbol: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    toggleArtifact: TypedContractMethod<
      [_designId: BigNumberish, _artifactIndex: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    tokenURI: TypedContractMethod<
      [tokenId: BigNumberish, ],
      [string],
      'view'
    >
    

    
    totalDesigns: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    transferFrom: TypedContractMethod<
      [from: AddressLike, to: AddressLike, tokenId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    updateArtifactPrice: TypedContractMethod<
      [_designId: BigNumberish, _artifactIndex: BigNumberish, _newPrice: BigNumberish, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'addArtifact'): TypedContractMethod<
      [_designId: BigNumberish, _name: string, _description: string, _priceInWei: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'approve'): TypedContractMethod<
      [to: AddressLike, tokenId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'artistDesigns'): TypedContractMethod<
      [arg0: AddressLike, arg1: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'balanceOf'): TypedContractMethod<
      [owner: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'calculateArtifactsCost'): TypedContractMethod<
      [_designId: BigNumberish, _artifactIds: BigNumberish[], ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'designArtifacts'): TypedContractMethod<
      [arg0: BigNumberish, arg1: BigNumberish, ],
      [[string, string, bigint, boolean] & {name: string, description: string, priceInWei: bigint, active: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'designs'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, string, string, string, string, bigint, bigint, boolean] & {artist: string, title: string, description: string, category: string, ipfsCid: string, thresholdPrice: bigint, createdAt: bigint, isPublic: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'getApproved'): TypedContractMethod<
      [tokenId: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getArtifactCount'): TypedContractMethod<
      [_designId: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getArtistDesigns'): TypedContractMethod<
      [_artist: AddressLike, ],
      [bigint[]],
      'view'
    >;
getFunction(nameOrSignature: 'getDesign'): TypedContractMethod<
      [_designId: BigNumberish, ],
      [DesignRegistry.DesignStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getDesignArtifacts'): TypedContractMethod<
      [_designId: BigNumberish, ],
      [DesignRegistry.ArtifactStructOutput[]],
      'view'
    >;
getFunction(nameOrSignature: 'isApprovedForAll'): TypedContractMethod<
      [owner: AddressLike, operator: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'mintDesign'): TypedContractMethod<
      [_title: string, _description: string, _category: string, _ipfsCid: string, _tags: string[], _tokenURI: string, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'name'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'ownerOf'): TypedContractMethod<
      [tokenId: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'safeTransferFrom(address,address,uint256)'): TypedContractMethod<
      [from: AddressLike, to: AddressLike, tokenId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'safeTransferFrom(address,address,uint256,bytes)'): TypedContractMethod<
      [from: AddressLike, to: AddressLike, tokenId: BigNumberish, data: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setApprovalForAll'): TypedContractMethod<
      [operator: AddressLike, approved: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'supportsInterface'): TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'symbol'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'toggleArtifact'): TypedContractMethod<
      [_designId: BigNumberish, _artifactIndex: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'tokenURI'): TypedContractMethod<
      [tokenId: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'totalDesigns'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'transferFrom'): TypedContractMethod<
      [from: AddressLike, to: AddressLike, tokenId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'updateArtifactPrice'): TypedContractMethod<
      [_designId: BigNumberish, _artifactIndex: BigNumberish, _newPrice: BigNumberish, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'Approval'): TypedContractEvent<ApprovalEvent.InputTuple, ApprovalEvent.OutputTuple, ApprovalEvent.OutputObject>;
getEvent(key: 'ApprovalForAll'): TypedContractEvent<ApprovalForAllEvent.InputTuple, ApprovalForAllEvent.OutputTuple, ApprovalForAllEvent.OutputObject>;
getEvent(key: 'ArtifactAdded'): TypedContractEvent<ArtifactAddedEvent.InputTuple, ArtifactAddedEvent.OutputTuple, ArtifactAddedEvent.OutputObject>;
getEvent(key: 'ArtifactUpdated'): TypedContractEvent<ArtifactUpdatedEvent.InputTuple, ArtifactUpdatedEvent.OutputTuple, ArtifactUpdatedEvent.OutputObject>;
getEvent(key: 'BatchMetadataUpdate'): TypedContractEvent<BatchMetadataUpdateEvent.InputTuple, BatchMetadataUpdateEvent.OutputTuple, BatchMetadataUpdateEvent.OutputObject>;
getEvent(key: 'DesignMinted'): TypedContractEvent<DesignMintedEvent.InputTuple, DesignMintedEvent.OutputTuple, DesignMintedEvent.OutputObject>;
getEvent(key: 'MetadataUpdate'): TypedContractEvent<MetadataUpdateEvent.InputTuple, MetadataUpdateEvent.OutputTuple, MetadataUpdateEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
getEvent(key: 'ThresholdPriceUpdated'): TypedContractEvent<ThresholdPriceUpdatedEvent.InputTuple, ThresholdPriceUpdatedEvent.OutputTuple, ThresholdPriceUpdatedEvent.OutputObject>;
getEvent(key: 'Transfer'): TypedContractEvent<TransferEvent.InputTuple, TransferEvent.OutputTuple, TransferEvent.OutputObject>;

    filters: {
      
      'Approval(address,address,uint256)': TypedContractEvent<ApprovalEvent.InputTuple, ApprovalEvent.OutputTuple, ApprovalEvent.OutputObject>;
      Approval: TypedContractEvent<ApprovalEvent.InputTuple, ApprovalEvent.OutputTuple, ApprovalEvent.OutputObject>;
    

      'ApprovalForAll(address,address,bool)': TypedContractEvent<ApprovalForAllEvent.InputTuple, ApprovalForAllEvent.OutputTuple, ApprovalForAllEvent.OutputObject>;
      ApprovalForAll: TypedContractEvent<ApprovalForAllEvent.InputTuple, ApprovalForAllEvent.OutputTuple, ApprovalForAllEvent.OutputObject>;
    

      'ArtifactAdded(uint256,uint256,string,uint256)': TypedContractEvent<ArtifactAddedEvent.InputTuple, ArtifactAddedEvent.OutputTuple, ArtifactAddedEvent.OutputObject>;
      ArtifactAdded: TypedContractEvent<ArtifactAddedEvent.InputTuple, ArtifactAddedEvent.OutputTuple, ArtifactAddedEvent.OutputObject>;
    

      'ArtifactUpdated(uint256,uint256,uint256)': TypedContractEvent<ArtifactUpdatedEvent.InputTuple, ArtifactUpdatedEvent.OutputTuple, ArtifactUpdatedEvent.OutputObject>;
      ArtifactUpdated: TypedContractEvent<ArtifactUpdatedEvent.InputTuple, ArtifactUpdatedEvent.OutputTuple, ArtifactUpdatedEvent.OutputObject>;
    

      'BatchMetadataUpdate(uint256,uint256)': TypedContractEvent<BatchMetadataUpdateEvent.InputTuple, BatchMetadataUpdateEvent.OutputTuple, BatchMetadataUpdateEvent.OutputObject>;
      BatchMetadataUpdate: TypedContractEvent<BatchMetadataUpdateEvent.InputTuple, BatchMetadataUpdateEvent.OutputTuple, BatchMetadataUpdateEvent.OutputObject>;
    

      'DesignMinted(uint256,address,string,string,uint256)': TypedContractEvent<DesignMintedEvent.InputTuple, DesignMintedEvent.OutputTuple, DesignMintedEvent.OutputObject>;
      DesignMinted: TypedContractEvent<DesignMintedEvent.InputTuple, DesignMintedEvent.OutputTuple, DesignMintedEvent.OutputObject>;
    

      'MetadataUpdate(uint256)': TypedContractEvent<MetadataUpdateEvent.InputTuple, MetadataUpdateEvent.OutputTuple, MetadataUpdateEvent.OutputObject>;
      MetadataUpdate: TypedContractEvent<MetadataUpdateEvent.InputTuple, MetadataUpdateEvent.OutputTuple, MetadataUpdateEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    

      'ThresholdPriceUpdated(uint256,uint256)': TypedContractEvent<ThresholdPriceUpdatedEvent.InputTuple, ThresholdPriceUpdatedEvent.OutputTuple, ThresholdPriceUpdatedEvent.OutputObject>;
      ThresholdPriceUpdated: TypedContractEvent<ThresholdPriceUpdatedEvent.InputTuple, ThresholdPriceUpdatedEvent.OutputTuple, ThresholdPriceUpdatedEvent.OutputObject>;
    

      'Transfer(address,address,uint256)': TypedContractEvent<TransferEvent.InputTuple, TransferEvent.OutputTuple, TransferEvent.OutputObject>;
      Transfer: TypedContractEvent<TransferEvent.InputTuple, TransferEvent.OutputTuple, TransferEvent.OutputObject>;
    
    };
  }