/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */


import { ethers } from 'ethers'
import { DeployContractOptions, FactoryOptions, HardhatEthersHelpers as HardhatEthersHelpersBase} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from "./index.js";

declare module "@nomicfoundation/hardhat-ethers/types" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
  getContractFactory(name: 'AgentRegistry', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.AgentRegistry__factory>
getContractFactory(name: 'AttributionPayment', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.AttributionPayment__factory>
getContractFactory(name: 'IAgentRegistry', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IAgentRegistry__factory>
getContractFactory(name: 'IDesignRegistry', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IDesignRegistry__factory>
getContractFactory(name: 'DesignRegistry', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.DesignRegistry__factory>
getContractFactory(name: 'ReputationForum', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.ReputationForum__factory>

  getContractAt(name: 'AgentRegistry', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.AgentRegistry>
getContractAt(name: 'AttributionPayment', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.AttributionPayment>
getContractAt(name: 'IAgentRegistry', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IAgentRegistry>
getContractAt(name: 'IDesignRegistry', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IDesignRegistry>
getContractAt(name: 'DesignRegistry', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.DesignRegistry>
getContractAt(name: 'ReputationForum', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.ReputationForum>

  deployContract(name: 'AgentRegistry', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.AgentRegistry>
deployContract(name: 'AttributionPayment', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.AttributionPayment>
deployContract(name: 'IAgentRegistry', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IAgentRegistry>
deployContract(name: 'IDesignRegistry', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IDesignRegistry>
deployContract(name: 'DesignRegistry', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.DesignRegistry>
deployContract(name: 'ReputationForum', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ReputationForum>

  deployContract(name: 'AgentRegistry', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.AgentRegistry>
deployContract(name: 'AttributionPayment', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.AttributionPayment>
deployContract(name: 'IAgentRegistry', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IAgentRegistry>
deployContract(name: 'IDesignRegistry', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IDesignRegistry>
deployContract(name: 'DesignRegistry', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.DesignRegistry>
deployContract(name: 'ReputationForum', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ReputationForum>

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
  