/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace ReputationForum {
      
    export type PostStruct = {id: BigNumberish, author: AddressLike, content: string, tags: string[], parentId: BigNumberish, createdAt: BigNumberish, upvotes: BigNumberish, downvotes: BigNumberish, isActive: boolean}

    export type PostStructOutput = [id: bigint, author: string, content: string, tags: string[], parentId: bigint, createdAt: bigint, upvotes: bigint, downvotes: bigint, isActive: boolean] & {id: bigint, author: string, content: string, tags: string[], parentId: bigint, createdAt: bigint, upvotes: bigint, downvotes: bigint, isActive: boolean }
  

    export type LiveEventStruct = {id: BigNumberish, eventType: string, actor: AddressLike, data: string, timestamp: BigNumberish}

    export type LiveEventStructOutput = [id: bigint, eventType: string, actor: string, data: string, timestamp: bigint] & {id: bigint, eventType: string, actor: string, data: string, timestamp: bigint }
  
    }

  export interface ReputationForumInterface extends Interface {
    getFunction(nameOrSignature: "createPost" | "emitPlatformEvent" | "getPost" | "getPostReplies" | "getRecentEvents" | "getRecentPosts" | "getUserPosts" | "hasVoted" | "liveEvents" | "postReplies" | "posts" | "removePost" | "reply" | "totalEvents" | "totalPosts" | "userPosts" | "vote"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "LiveEventEmitted" | "PostCreated" | "PostRemoved" | "PostVoted"): EventFragment;

    encodeFunctionData(functionFragment: 'createPost', values: [string, string[]]): string;
encodeFunctionData(functionFragment: 'emitPlatformEvent', values: [string, string]): string;
encodeFunctionData(functionFragment: 'getPost', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getPostReplies', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getRecentEvents', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getRecentPosts', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getUserPosts', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'hasVoted', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'liveEvents', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'postReplies', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'posts', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'removePost', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'reply', values: [BigNumberish, string]): string;
encodeFunctionData(functionFragment: 'totalEvents', values?: undefined): string;
encodeFunctionData(functionFragment: 'totalPosts', values?: undefined): string;
encodeFunctionData(functionFragment: 'userPosts', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'vote', values: [BigNumberish, boolean]): string;

    decodeFunctionResult(functionFragment: 'createPost', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'emitPlatformEvent', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getPost', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getPostReplies', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getRecentEvents', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getRecentPosts', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getUserPosts', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hasVoted', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'liveEvents', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'postReplies', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'posts', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'removePost', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'reply', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalEvents', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalPosts', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'userPosts', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'vote', data: BytesLike): Result;
  }

  
    export namespace LiveEventEmittedEvent {
      export type InputTuple = [eventId: BigNumberish, eventType: string, actor: AddressLike, data: string, timestamp: BigNumberish];
      export type OutputTuple = [eventId: bigint, eventType: string, actor: string, data: string, timestamp: bigint];
      export interface OutputObject {eventId: bigint, eventType: string, actor: string, data: string, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PostCreatedEvent {
      export type InputTuple = [postId: BigNumberish, author: AddressLike, content: string, tags: string[], parentId: BigNumberish, timestamp: BigNumberish];
      export type OutputTuple = [postId: bigint, author: string, content: string, tags: string[], parentId: bigint, timestamp: bigint];
      export interface OutputObject {postId: bigint, author: string, content: string, tags: string[], parentId: bigint, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PostRemovedEvent {
      export type InputTuple = [postId: BigNumberish, author: AddressLike, timestamp: BigNumberish];
      export type OutputTuple = [postId: bigint, author: string, timestamp: bigint];
      export interface OutputObject {postId: bigint, author: string, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PostVotedEvent {
      export type InputTuple = [postId: BigNumberish, voter: AddressLike, isUpvote: boolean, timestamp: BigNumberish];
      export type OutputTuple = [postId: bigint, voter: string, isUpvote: boolean, timestamp: bigint];
      export interface OutputObject {postId: bigint, voter: string, isUpvote: boolean, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface ReputationForum extends BaseContract {
    
    connect(runner?: ContractRunner | null): ReputationForum;
    waitForDeployment(): Promise<this>;

    interface: ReputationForumInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    createPost: TypedContractMethod<
      [_content: string, _tags: string[], ],
      [bigint],
      'nonpayable'
    >
    

    
    emitPlatformEvent: TypedContractMethod<
      [_eventType: string, _data: string, ],
      [void],
      'nonpayable'
    >
    

    
    getPost: TypedContractMethod<
      [_postId: BigNumberish, ],
      [ReputationForum.PostStructOutput],
      'view'
    >
    

    
    getPostReplies: TypedContractMethod<
      [_postId: BigNumberish, ],
      [bigint[]],
      'view'
    >
    

    
    getRecentEvents: TypedContractMethod<
      [_count: BigNumberish, ],
      [ReputationForum.LiveEventStructOutput[]],
      'view'
    >
    

    
    getRecentPosts: TypedContractMethod<
      [_count: BigNumberish, ],
      [ReputationForum.PostStructOutput[]],
      'view'
    >
    

    
    getUserPosts: TypedContractMethod<
      [_user: AddressLike, ],
      [bigint[]],
      'view'
    >
    

    
    hasVoted: TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    liveEvents: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, string, string, string, bigint] & {id: bigint, eventType: string, actor: string, data: string, timestamp: bigint }],
      'view'
    >
    

    
    postReplies: TypedContractMethod<
      [arg0: BigNumberish, arg1: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    posts: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, string, string, bigint, bigint, bigint, bigint, boolean] & {id: bigint, author: string, content: string, parentId: bigint, createdAt: bigint, upvotes: bigint, downvotes: bigint, isActive: boolean }],
      'view'
    >
    

    
    removePost: TypedContractMethod<
      [_postId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    reply: TypedContractMethod<
      [_parentId: BigNumberish, _content: string, ],
      [bigint],
      'nonpayable'
    >
    

    
    totalEvents: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    totalPosts: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    userPosts: TypedContractMethod<
      [arg0: AddressLike, arg1: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    vote: TypedContractMethod<
      [_postId: BigNumberish, _isUpvote: boolean, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'createPost'): TypedContractMethod<
      [_content: string, _tags: string[], ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'emitPlatformEvent'): TypedContractMethod<
      [_eventType: string, _data: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getPost'): TypedContractMethod<
      [_postId: BigNumberish, ],
      [ReputationForum.PostStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getPostReplies'): TypedContractMethod<
      [_postId: BigNumberish, ],
      [bigint[]],
      'view'
    >;
getFunction(nameOrSignature: 'getRecentEvents'): TypedContractMethod<
      [_count: BigNumberish, ],
      [ReputationForum.LiveEventStructOutput[]],
      'view'
    >;
getFunction(nameOrSignature: 'getRecentPosts'): TypedContractMethod<
      [_count: BigNumberish, ],
      [ReputationForum.PostStructOutput[]],
      'view'
    >;
getFunction(nameOrSignature: 'getUserPosts'): TypedContractMethod<
      [_user: AddressLike, ],
      [bigint[]],
      'view'
    >;
getFunction(nameOrSignature: 'hasVoted'): TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'liveEvents'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, string, string, string, bigint] & {id: bigint, eventType: string, actor: string, data: string, timestamp: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'postReplies'): TypedContractMethod<
      [arg0: BigNumberish, arg1: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'posts'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, string, string, bigint, bigint, bigint, bigint, boolean] & {id: bigint, author: string, content: string, parentId: bigint, createdAt: bigint, upvotes: bigint, downvotes: bigint, isActive: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'removePost'): TypedContractMethod<
      [_postId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'reply'): TypedContractMethod<
      [_parentId: BigNumberish, _content: string, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'totalEvents'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'totalPosts'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'userPosts'): TypedContractMethod<
      [arg0: AddressLike, arg1: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'vote'): TypedContractMethod<
      [_postId: BigNumberish, _isUpvote: boolean, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'LiveEventEmitted'): TypedContractEvent<LiveEventEmittedEvent.InputTuple, LiveEventEmittedEvent.OutputTuple, LiveEventEmittedEvent.OutputObject>;
getEvent(key: 'PostCreated'): TypedContractEvent<PostCreatedEvent.InputTuple, PostCreatedEvent.OutputTuple, PostCreatedEvent.OutputObject>;
getEvent(key: 'PostRemoved'): TypedContractEvent<PostRemovedEvent.InputTuple, PostRemovedEvent.OutputTuple, PostRemovedEvent.OutputObject>;
getEvent(key: 'PostVoted'): TypedContractEvent<PostVotedEvent.InputTuple, PostVotedEvent.OutputTuple, PostVotedEvent.OutputObject>;

    filters: {
      
      'LiveEventEmitted(uint256,string,address,string,uint256)': TypedContractEvent<LiveEventEmittedEvent.InputTuple, LiveEventEmittedEvent.OutputTuple, LiveEventEmittedEvent.OutputObject>;
      LiveEventEmitted: TypedContractEvent<LiveEventEmittedEvent.InputTuple, LiveEventEmittedEvent.OutputTuple, LiveEventEmittedEvent.OutputObject>;
    

      'PostCreated(uint256,address,string,string[],uint256,uint256)': TypedContractEvent<PostCreatedEvent.InputTuple, PostCreatedEvent.OutputTuple, PostCreatedEvent.OutputObject>;
      PostCreated: TypedContractEvent<PostCreatedEvent.InputTuple, PostCreatedEvent.OutputTuple, PostCreatedEvent.OutputObject>;
    

      'PostRemoved(uint256,address,uint256)': TypedContractEvent<PostRemovedEvent.InputTuple, PostRemovedEvent.OutputTuple, PostRemovedEvent.OutputObject>;
      PostRemoved: TypedContractEvent<PostRemovedEvent.InputTuple, PostRemovedEvent.OutputTuple, PostRemovedEvent.OutputObject>;
    

      'PostVoted(uint256,address,bool,uint256)': TypedContractEvent<PostVotedEvent.InputTuple, PostVotedEvent.OutputTuple, PostVotedEvent.OutputObject>;
      PostVoted: TypedContractEvent<PostVotedEvent.InputTuple, PostVotedEvent.OutputTuple, PostVotedEvent.OutputObject>;
    
    };
  }