/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IDesignRegistry, IDesignRegistryInterface } from "../../AttributionPayment.sol/IDesignRegistry.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "_designId",
        "type": "uint256"
      },
      {
        "internalType": "uint256[]",
        "name": "_artifactIds",
        "type": "uint256[]"
      }
    ],
    "name": "calculateArtifactsCost",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "_designId",
        "type": "uint256"
      }
    ],
    "name": "getDesign",
    "outputs": [
      {
        "components": [
          {
            "internalType": "address",
            "name": "artist",
            "type": "address"
          },
          {
            "internalType": "string",
            "name": "title",
            "type": "string"
          },
          {
            "internalType": "string",
            "name": "description",
            "type": "string"
          },
          {
            "internalType": "string",
            "name": "category",
            "type": "string"
          },
          {
            "internalType": "string",
            "name": "ipfsCid",
            "type": "string"
          },
          {
            "internalType": "string[]",
            "name": "tags",
            "type": "string[]"
          },
          {
            "internalType": "uint256",
            "name": "thresholdPrice",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "createdAt",
            "type": "uint256"
          },
          {
            "internalType": "bool",
            "name": "isPublic",
            "type": "bool"
          }
        ],
        "internalType": "struct IDesignRegistry.Design",
        "name": "",
        "type": "tuple"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "_designId",
        "type": "uint256"
      }
    ],
    "name": "getDesignArtifacts",
    "outputs": [
      {
        "components": [
          {
            "internalType": "string",
            "name": "name",
            "type": "string"
          },
          {
            "internalType": "string",
            "name": "description",
            "type": "string"
          },
          {
            "internalType": "uint256",
            "name": "priceInWei",
            "type": "uint256"
          },
          {
            "internalType": "bool",
            "name": "active",
            "type": "bool"
          }
        ],
        "internalType": "struct IDesignRegistry.Artifact[]",
        "name": "",
        "type": "tuple[]"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "tokenId",
        "type": "uint256"
      }
    ],
    "name": "ownerOf",
    "outputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;

  export class IDesignRegistry__factory {
    static readonly abi = _abi;
    static createInterface(): IDesignRegistryInterface {
      return new Interface(_abi) as IDesignRegistryInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): IDesignRegistry {
      return new Contract(address, _abi, runner) as unknown as IDesignRegistry;
    }
  }
  