/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  
export declare namespace AttributionPayment {
      
    export type AttributionStruct = {designId: BigNumberish, clientAgent: AddressLike, artistAgent: AddressLike, artist: AddressLike, artifactIds: BigNumberish[], totalPaid: BigNumberish, x402ProofHash: BytesLike, timestamp: BigNumberish}

    export type AttributionStructOutput = [designId: bigint, clientAgent: string, artistAgent: string, artist: string, artifactIds: bigint[], totalPaid: bigint, x402ProofHash: string, timestamp: bigint] & {designId: bigint, clientAgent: string, artistAgent: string, artist: string, artifactIds: bigint[], totalPaid: bigint, x402ProofHash: string, timestamp: bigint }
  
    }

  export interface AttributionPaymentInterface extends Interface {
    getFunction(nameOrSignature: "agentRegistry" | "artistAttributions" | "attributions" | "clientAttributions" | "designAttributions" | "designRegistry" | "getArtistAttributions" | "getAttribution" | "getAttributionCount" | "getClientAttributions" | "getDesignAttributionHistory" | "getStats" | "payForArtifacts" | "totalPayments" | "totalVolume"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "AttributionPaid" | "PaymentReceived"): EventFragment;

    encodeFunctionData(functionFragment: 'agentRegistry', values?: undefined): string;
encodeFunctionData(functionFragment: 'artistAttributions', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'attributions', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'clientAttributions', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'designAttributions', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'designRegistry', values?: undefined): string;
encodeFunctionData(functionFragment: 'getArtistAttributions', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getAttribution', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getAttributionCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'getClientAttributions', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getDesignAttributionHistory', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getStats', values?: undefined): string;
encodeFunctionData(functionFragment: 'payForArtifacts', values: [BigNumberish, BigNumberish[], BytesLike]): string;
encodeFunctionData(functionFragment: 'totalPayments', values?: undefined): string;
encodeFunctionData(functionFragment: 'totalVolume', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'agentRegistry', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'artistAttributions', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'attributions', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'clientAttributions', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'designAttributions', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'designRegistry', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getArtistAttributions', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getAttribution', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getAttributionCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getClientAttributions', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getDesignAttributionHistory', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getStats', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'payForArtifacts', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalPayments', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalVolume', data: BytesLike): Result;
  }

  
    export namespace AttributionPaidEvent {
      export type InputTuple = [attributionId: BigNumberish, designId: BigNumberish, artist: AddressLike, clientAgent: AddressLike, artifactIds: BigNumberish[], totalPaid: BigNumberish, x402ProofHash: BytesLike, timestamp: BigNumberish];
      export type OutputTuple = [attributionId: bigint, designId: bigint, artist: string, clientAgent: string, artifactIds: bigint[], totalPaid: bigint, x402ProofHash: string, timestamp: bigint];
      export interface OutputObject {attributionId: bigint, designId: bigint, artist: string, clientAgent: string, artifactIds: bigint[], totalPaid: bigint, x402ProofHash: string, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PaymentReceivedEvent {
      export type InputTuple = [artist: AddressLike, amount: BigNumberish, designId: BigNumberish, timestamp: BigNumberish];
      export type OutputTuple = [artist: string, amount: bigint, designId: bigint, timestamp: bigint];
      export interface OutputObject {artist: string, amount: bigint, designId: bigint, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface AttributionPayment extends BaseContract {
    
    connect(runner?: ContractRunner | null): AttributionPayment;
    waitForDeployment(): Promise<this>;

    interface: AttributionPaymentInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    agentRegistry: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    artistAttributions: TypedContractMethod<
      [arg0: AddressLike, arg1: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    attributions: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, string, string, string, bigint, string, bigint] & {designId: bigint, clientAgent: string, artistAgent: string, artist: string, totalPaid: bigint, x402ProofHash: string, timestamp: bigint }],
      'view'
    >
    

    
    clientAttributions: TypedContractMethod<
      [arg0: AddressLike, arg1: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    designAttributions: TypedContractMethod<
      [arg0: BigNumberish, arg1: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    designRegistry: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    getArtistAttributions: TypedContractMethod<
      [_artist: AddressLike, ],
      [bigint[]],
      'view'
    >
    

    
    getAttribution: TypedContractMethod<
      [_id: BigNumberish, ],
      [AttributionPayment.AttributionStructOutput],
      'view'
    >
    

    
    getAttributionCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    getClientAttributions: TypedContractMethod<
      [_client: AddressLike, ],
      [bigint[]],
      'view'
    >
    

    
    getDesignAttributionHistory: TypedContractMethod<
      [_designId: BigNumberish, ],
      [bigint[]],
      'view'
    >
    

    
    getStats: TypedContractMethod<
      [],
      [[bigint, bigint, bigint] & {_totalPayments: bigint, _totalVolume: bigint, _totalAttributions: bigint }],
      'view'
    >
    

    
    payForArtifacts: TypedContractMethod<
      [_designId: BigNumberish, _artifactIds: BigNumberish[], _x402ProofHash: BytesLike, ],
      [bigint],
      'payable'
    >
    

    
    totalPayments: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    totalVolume: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'agentRegistry'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'artistAttributions'): TypedContractMethod<
      [arg0: AddressLike, arg1: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'attributions'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, string, string, string, bigint, string, bigint] & {designId: bigint, clientAgent: string, artistAgent: string, artist: string, totalPaid: bigint, x402ProofHash: string, timestamp: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'clientAttributions'): TypedContractMethod<
      [arg0: AddressLike, arg1: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'designAttributions'): TypedContractMethod<
      [arg0: BigNumberish, arg1: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'designRegistry'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getArtistAttributions'): TypedContractMethod<
      [_artist: AddressLike, ],
      [bigint[]],
      'view'
    >;
getFunction(nameOrSignature: 'getAttribution'): TypedContractMethod<
      [_id: BigNumberish, ],
      [AttributionPayment.AttributionStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getAttributionCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getClientAttributions'): TypedContractMethod<
      [_client: AddressLike, ],
      [bigint[]],
      'view'
    >;
getFunction(nameOrSignature: 'getDesignAttributionHistory'): TypedContractMethod<
      [_designId: BigNumberish, ],
      [bigint[]],
      'view'
    >;
getFunction(nameOrSignature: 'getStats'): TypedContractMethod<
      [],
      [[bigint, bigint, bigint] & {_totalPayments: bigint, _totalVolume: bigint, _totalAttributions: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'payForArtifacts'): TypedContractMethod<
      [_designId: BigNumberish, _artifactIds: BigNumberish[], _x402ProofHash: BytesLike, ],
      [bigint],
      'payable'
    >;
getFunction(nameOrSignature: 'totalPayments'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'totalVolume'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;

    getEvent(key: 'AttributionPaid'): TypedContractEvent<AttributionPaidEvent.InputTuple, AttributionPaidEvent.OutputTuple, AttributionPaidEvent.OutputObject>;
getEvent(key: 'PaymentReceived'): TypedContractEvent<PaymentReceivedEvent.InputTuple, PaymentReceivedEvent.OutputTuple, PaymentReceivedEvent.OutputObject>;

    filters: {
      
      'AttributionPaid(uint256,uint256,address,address,uint256[],uint256,bytes32,uint256)': TypedContractEvent<AttributionPaidEvent.InputTuple, AttributionPaidEvent.OutputTuple, AttributionPaidEvent.OutputObject>;
      AttributionPaid: TypedContractEvent<AttributionPaidEvent.InputTuple, AttributionPaidEvent.OutputTuple, AttributionPaidEvent.OutputObject>;
    

      'PaymentReceived(address,uint256,uint256,uint256)': TypedContractEvent<PaymentReceivedEvent.InputTuple, PaymentReceivedEvent.OutputTuple, PaymentReceivedEvent.OutputObject>;
      PaymentReceived: TypedContractEvent<PaymentReceivedEvent.InputTuple, PaymentReceivedEvent.OutputTuple, PaymentReceivedEvent.OutputObject>;
    
    };
  }