/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BytesLike, FunctionFragment, Result, Interface, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface IAgentRegistryInterface extends Interface {
    getFunction(nameOrSignature: "isRegisteredAgent" | "walletToAgentId"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'isRegisteredAgent', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'walletToAgentId', values: [AddressLike]): string;

    decodeFunctionResult(functionFragment: 'isRegisteredAgent', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'walletToAgentId', data: BytesLike): Result;
  }

  

  export interface IAgentRegistry extends BaseContract {
    
    connect(runner?: ContractRunner | null): IAgentRegistry;
    waitForDeployment(): Promise<this>;

    interface: IAgentRegistryInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    isRegisteredAgent: TypedContractMethod<
      [_wallet: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    walletToAgentId: TypedContractMethod<
      [_wallet: AddressLike, ],
      [bigint],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'isRegisteredAgent'): TypedContractMethod<
      [_wallet: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'walletToAgentId'): TypedContractMethod<
      [_wallet: AddressLike, ],
      [bigint],
      'view'
    >;

    

    filters: {
      
    };
  }