/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../common.js"
  
export declare namespace IDesignRegistry {
      
    export type DesignStruct = {artist: AddressLike, title: string, description: string, category: string, ipfsCid: string, tags: string[], thresholdPrice: BigNumberish, createdAt: BigNumberish, isPublic: boolean}

    export type DesignStructOutput = [artist: string, title: string, description: string, category: string, ipfsCid: string, tags: string[], thresholdPrice: bigint, createdAt: bigint, isPublic: boolean] & {artist: string, title: string, description: string, category: string, ipfsCid: string, tags: string[], thresholdPrice: bigint, createdAt: bigint, isPublic: boolean }
  

    export type ArtifactStruct = {name: string, description: string, priceInWei: BigNumberish, active: boolean}

    export type ArtifactStructOutput = [name: string, description: string, priceInWei: bigint, active: boolean] & {name: string, description: string, priceInWei: bigint, active: boolean }
  
    }

  export interface IDesignRegistryInterface extends Interface {
    getFunction(nameOrSignature: "calculateArtifactsCost" | "getDesign" | "getDesignArtifacts" | "ownerOf"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'calculateArtifactsCost', values: [BigNumberish, BigNumberish[]]): string;
encodeFunctionData(functionFragment: 'getDesign', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getDesignArtifacts', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'ownerOf', values: [BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'calculateArtifactsCost', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getDesign', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getDesignArtifacts', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'ownerOf', data: BytesLike): Result;
  }

  

  export interface IDesignRegistry extends BaseContract {
    
    connect(runner?: ContractRunner | null): IDesignRegistry;
    waitForDeployment(): Promise<this>;

    interface: IDesignRegistryInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    calculateArtifactsCost: TypedContractMethod<
      [_designId: BigNumberish, _artifactIds: BigNumberish[], ],
      [bigint],
      'view'
    >
    

    
    getDesign: TypedContractMethod<
      [_designId: BigNumberish, ],
      [IDesignRegistry.DesignStructOutput],
      'view'
    >
    

    
    getDesignArtifacts: TypedContractMethod<
      [_designId: BigNumberish, ],
      [IDesignRegistry.ArtifactStructOutput[]],
      'view'
    >
    

    
    ownerOf: TypedContractMethod<
      [tokenId: BigNumberish, ],
      [string],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'calculateArtifactsCost'): TypedContractMethod<
      [_designId: BigNumberish, _artifactIds: BigNumberish[], ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getDesign'): TypedContractMethod<
      [_designId: BigNumberish, ],
      [IDesignRegistry.DesignStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getDesignArtifacts'): TypedContractMethod<
      [_designId: BigNumberish, ],
      [IDesignRegistry.ArtifactStructOutput[]],
      'view'
    >;
getFunction(nameOrSignature: 'ownerOf'): TypedContractMethod<
      [tokenId: BigNumberish, ],
      [string],
      'view'
    >;

    

    filters: {
      
    };
  }